{
  "uid" : "369227e589348e29",
  "name" : "test_01_login",
  "fullName" : "case.test_02login#test_01_login",
  "historyId" : "2f83e8f611a3fd60dab34befca7f4863",
  "time" : {
    "start" : 1596333594063,
    "stop" : 1596333594173,
    "duration" : 110
  },
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "6e9546f90669b70d",
      "name" : "stdout",
      "source" : "6e9546f90669b70d.txt",
      "type" : "text/plain",
      "size" : 276
    } ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 1,
    "hasContent" : true,
    "stepsCount" : 0
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "case"
  }, {
    "name" : "suite",
    "value" : "test_02login"
  }, {
    "name" : "host",
    "value" : "RTSK58I13S6V3IN"
  }, {
    "name" : "thread",
    "value" : "4304-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "case.test_02login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "aa29f16b4ff78004",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert 500 == 200\n +  where 500 = <Response [500]>.status_code",
      "time" : {
        "start" : 1596333541621,
        "stop" : 1596333541691,
        "duration" : 70
      }
    }, {
      "uid" : "1eb2bcdda4ff0812",
      "status" : "failed",
      "statusDetails" : "AssertionError: assert 500 == 200\n +  where 500 = <Response [500]>.status_code",
      "time" : {
        "start" : 1596333303760,
        "stop" : 1596333303849,
        "duration" : 89
      }
    }, {
      "uid" : "1d9f9a8b12361401",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='49.232.185.181', port=2333): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025B9876D970>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1596332909527,
        "stop" : 1596332930541,
        "duration" : 21014
      }
    }, {
      "uid" : "9dce0ddede90a7f9",
      "status" : "passed",
      "time" : {
        "start" : 1596292106567,
        "stop" : 1596292106674,
        "duration" : 107
      }
    }, {
      "uid" : "e5b24747fca6a9f0",
      "status" : "passed",
      "time" : {
        "start" : 1596292059805,
        "stop" : 1596292059912,
        "duration" : 107
      }
    }, {
      "uid" : "7f06aaf46ea57a8c",
      "status" : "passed",
      "time" : {
        "start" : 1596291458530,
        "stop" : 1596291458657,
        "duration" : 127
      }
    }, {
      "uid" : "4ebaf9e4d9e81188",
      "status" : "passed",
      "time" : {
        "start" : 1596291242448,
        "stop" : 1596291242554,
        "duration" : 106
      }
    }, {
      "uid" : "f384f2afbc8c7c0b",
      "status" : "passed",
      "time" : {
        "start" : 1596290943091,
        "stop" : 1596290943199,
        "duration" : 108
      }
    }, {
      "uid" : "d513b344ca15f583",
      "status" : "passed",
      "time" : {
        "start" : 1596290642707,
        "stop" : 1596290642826,
        "duration" : 119
      }
    }, {
      "uid" : "7b69f369fda8e556",
      "status" : "passed",
      "time" : {
        "start" : 1596290450267,
        "stop" : 1596290450387,
        "duration" : 120
      }
    }, {
      "uid" : "4c3baf13c2615cd1",
      "status" : "passed",
      "time" : {
        "start" : 1596290342405,
        "stop" : 1596290343030,
        "duration" : 625
      }
    }, {
      "uid" : "756e820ceb4b01d5",
      "status" : "passed",
      "time" : {
        "start" : 1596290172875,
        "stop" : 1596290172980,
        "duration" : 105
      }
    }, {
      "uid" : "404f3774a31d502e",
      "status" : "passed",
      "time" : {
        "start" : 1596290114857,
        "stop" : 1596290114949,
        "duration" : 92
      }
    }, {
      "uid" : "ffc8ecea4a0a79f5",
      "status" : "passed",
      "time" : {
        "start" : 1596290042463,
        "stop" : 1596290042565,
        "duration" : 102
      }
    }, {
      "uid" : "c9b4e57e4282c35f",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='49.232.185.181', port=2333): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000221E6D19460>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1596289743801,
        "stop" : 1596289764824,
        "duration" : 21023
      }
    }, {
      "uid" : "82c356fdc83043bd",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='49.232.185.181', port=2333): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C58F8CA7C0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1596289625534,
        "stop" : 1596289646560,
        "duration" : 21026
      }
    }, {
      "uid" : "7e795a0f694f8e36",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='49.232.185.181', port=2333): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A49728280>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1596289445039,
        "stop" : 1596289466158,
        "duration" : 21119
      }
    }, {
      "uid" : "f6b63fe5694bc309",
      "status" : "broken",
      "statusDetails" : "requests.exceptions.ConnectionError: HTTPConnectionPool(host='49.232.185.181', port=2333): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023F21691100>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))",
      "time" : {
        "start" : 1596289285135,
        "stop" : 1596289306206,
        "duration" : 21071
      }
    } ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 2,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 1,
        "unknown" : 0,
        "total" : 3
      },
      "items" : [ {
        "uid" : "e993a550e033c321",
        "reportUrl" : "http://localhost:8080/job/aller_pytest_auto/3/allure/#testresult/e993a550e033c321",
        "status" : "failed",
        "statusDetails" : "AssertionError: assert 500 == 200\n +  where 500 = <Response [500]>.status_code",
        "time" : {
          "start" : 1596333541621,
          "stop" : 1596333541691,
          "duration" : 70
        }
      }, {
        "uid" : "864e1dd8ba03f99a",
        "reportUrl" : "http://localhost:8080/job/aller_pytest_auto/2/allure/#testresult/864e1dd8ba03f99a",
        "status" : "failed",
        "statusDetails" : "AssertionError: assert 500 == 200\n +  where 500 = <Response [500]>.status_code",
        "time" : {
          "start" : 1596333303760,
          "stop" : 1596333303849,
          "duration" : 89
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "369227e589348e29.json",
  "parameterValues" : [ ]
}